### ISSUE TITLE
优雅地调试OpenStack

### ISSUE THREAD

**Issue by Yikun** [Yikun/yikun.github.com#47]
恩，题目首先要起的高逼格一些。2333。

**Comment by bibapple** [comment]
请问你的screen -x stack命令执行了，出现的截图是怎么搞出来的？我的虚拟机安装了devstack的openstack之后，输入命令screen -x stack，没出现这些个进程呢？还报下面的错：
stack@xh-virtual-machine:~/devstack$ screen -x stack
There is no screen to be attached matching stack.

**Comment by Yikun** [comment]
@bibapple 目前社区已经废弃了screen这种方式来启动进程了（参考[Remove screen support from devstack completely](https://review.openstack.org/#/c/499186/)），原因是OpenStack需要管理的进程太多了，screen已没有“能力”去管理。

社区已经切换到systemd来进行进程管理，可以参考官方提供的[Using Systemd in DevStack](https://docs.openstack.org/devstack/latest/systemd.html)一文来入门。

**Comment by bibapple** [comment]
@Yikun多谢你的指点，我去研究研究官方文档。再请问下API的调试还是上面你写的方法吗？还是说也有些变化呢？

**Comment by Yikun** [comment]
@bibapple 参考systemd的[debugging](https://docs.openstack.org/devstack/latest/systemd.html#debugging)一节，这个调试更方便，目前我是使用pdb的方式多一些。

**Comment by bibapple** [comment]
@Yikun谢谢你的指点，我去研究研究pdb调试。

**Comment by bibapple** [comment]
@Yikun我这两天都在研究devstack的pdb调试，但是下面这个问题差了好多资料都没搞定，请教一下你是怎么弄得呢？

1月 23 10:00:56 xh-virtual-machine devstack@keystone.service[5543]: (Pdb)
1月 23 10:00:56 xh-virtual-machine devstack@keystone.service[5543]: ERROR keystone.common.wsgi [None req-9510783d-ef6a-4615-8e21-e4b5925fdec9 None None] : BdbQuit
1月 23 10:00:56 xh-virtual-machine devstack@keystone.service[5543]: ERROR keystone.common.wsgi Traceback (most recent call last):
1月 23 10:00:56 xh-virtual-machine devstack@keystone.service[5543]: ERROR keystone.common.wsgi   File "/opt/stack/keystone/keystone/common/wsgi.py", line 352, in _inner
1月 23 10:00:56 xh-virtual-machine devstack@keystone.service[5543]: ERROR keystone.common.wsgi     return method(self, request)
1月 23 10:00:56 xh-virtual-machine devstack@keystone.service[5543]: ERROR keystone.common.wsgi   File "/opt/stack/keystone/keystone/middleware/auth.py", line 166, in process_request
1月 23 10:00:56 xh-virtual-machine devstack@keystone.service[5543]: ERROR keystone.common.wsgi     self.fill_context(request)
1月 23 10:00:56 xh-virtual-machine devstack@keystone.service[5543]: ERROR keystone.common.wsgi   File "/opt/stack/keystone/keystone/middleware/auth.py", line 191, in fill_context
1月 23 10:00:56 xh-virtual-machine devstack@keystone.service[5543]: ERROR keystone.common.wsgi     if request.environ.get(core.CONTEXT_ENV, {}).get('is_admin', False):
1月 23 10:00:56 xh-virtual-machine devstack@keystone.service[5543]: ERROR keystone.common.wsgi   File "/opt/stack/keystone/keystone/middleware/auth.py", line 191, in fill_context
1月 23 10:00:56 xh-virtual-machine devstack@keystone.service[5543]: ERROR keystone.common.wsgi     if request.environ.get(core.CONTEXT_ENV, {}).get('is_admin', False):
1月 23 10:00:56 xh-virtual-machine devstack@keystone.service[5543]: ERROR keystone.common.wsgi   File "/usr/lib/python2.7/bdb.py", line 49, in trace_dispatch
1月 23 10:00:56 xh-virtual-machine devstack@keystone.service[5543]: ERROR keystone.common.wsgi     return self.dispatch_line(frame)
1月 23 10:00:56 xh-virtual-machine devstack@keystone.service[5543]: ERROR keystone.common.wsgi   File "/usr/lib/python2.7/bdb.py", line 68, in dispatch_line
1月 23 10:00:56 xh-virtual-machine devstack@keystone.service[5543]: ERROR keystone.common.wsgi     if self.quitting: raise BdbQuit
1月 23 10:00:56 xh-virtual-machine devstack@keystone.service[5543]: ERROR keystone.common.wsgi BdbQuit

**Comment by Yikun** [comment]
@bibapple 

> systemctl show devstack@keystone.service -p ExecStart --no-pager
> 
> ExecStart={ path=/usr/local/bin/uwsgi ; argv[]=**/usr/local/bin/uwsgi --procname-prefix keystone --ini /etc/keystone/keystone-uwsgi-public.ini** ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }

可以通过`systemctl show`去看执行的命令，WSGI比较特殊些，需要加一个`--honour-stdin`进行调试。即
> /usr/local/bin/uwsgi --procname-prefix keystone --ini /etc/keystone/keystone-uwsgi-public.ini --honour-stdin

**Comment by bibapple** [comment]
@Yikun多谢大神，现在貌似可以调试起来了，希望以后可以多和大神交流交流^-^

**Comment by Yikun** [comment]
```
[[install]]


[[local|localrc]]
GIT_BASE=https://github.com

#SSL
#USE_SSL=True
#SSL_ENABLED_SERVICES=glance

# Define the devstack install directory
#DEST=/opt/stack/
#Data directory
#DATA_DIR=/opt/stack/data/
#Service dirctory
#SERVICE_DIR=$DEST/service

# No internet
#OFFLINE=True
#Reclone
RECLONE=True

ADMIN_PASSWORD=1
MYSQL_PASSWORD=$ADMIN_PASSWORD
RABBIT_PASSWORD=$ADMIN_PASSWORD
SERVICE_PASSWORD=$ADMIN_PASSWORD

# Using milestone-proposed branches
#CINDER_BRANCH=stable/juno
#GLANCE_BRANCH=stable/juno
#KEYSTONE_BRANCH=stable/juno
#NOVA_BRANCH=stable/juno
#NEUTRON_BRANCH=stable/juno
#CEILOMETER_BRANCH=stable/juno
#HORIZON_BRANCH=stable/juno
#REQUIREMENTS_BRANCH=stable/juno

# ``HOST_IP`` should be set manually for best results if the NIC configuration
# of the host is unusual, i.e. ``eth1`` has the default route but ``eth0`` is the
# public interface.  It is auto-detected in ``stack.sh`` but often is indeterminate
# on later runs due to the IP moving from an Ethernet interface to a bridge on
# the host. Setting it here also makes it available for ``openrc`` to include
# when setting ``OS_AUTH_URL``.
# ``HOST_IP`` is not set by default.
#HOST_IP=w.x.y.z

# Logging
# -------
# By default ``stack.sh`` output only goes to the terminal where it runs.  It can
# be configured to additionally log to a file by setting ``LOGFILE`` to the full
# path of the destination log file.  A timestamp will be appended to the given name.
LOGFILE=$DEST/logs/stack.sh.log
# Old log files are automatically removed after 7 days to keep things neat.  Change
# the number of days by setting ``LOGDAYS``.
LOGDAYS=2
# Nova logs will be colorized if ``SYSLOG`` is not set; turn this off by setting
# ``LOG_COLOR`` false.
#LOG_COLOR=False
#------------------------------------------------------------------------------
# disable all services first if you don't want to install the default services.
# disable_all_services
#------------------------------------------------------------------------------
# Pre-requisite
enable_service rabbit mysql key
#enable_service -mysql postgresql
#------------------------------------------------------------------------------
#Libraries from Git
LIBS_FROM_GIT=python-openstackclient,python-keystoneclient,python-glanceclient,python-novaclient,python-cinderclient
#------------------------------------------------------------------------------
# Keystone
KEYSTONE_TOKEN_FORMAT=fernet
#KEYSTONE_DEPLOY=uwsgi

# OpenLdap, this will create a domain in keystone using openldap as the identity driver.
# enable_service ldap
# Federation, this will set the Keystone as Service Provider, and use testshib.org
# as Identity Provider
# enable_service keystone-saml2-federation
# Placement
enable_service placement,placement-client
#------------------------------------------------------------------------------
# Nova
enable_service n-api n-obj n-cpu n-cond n-sch n-schi n-novnc n-cauth
#------------------------------------------------------------------------------
# Cinder
enable_service cinder c-api c-vol c-sch c-bak
#------------------------------------------------------------------------------
# Neutron
enable_service q-svc q-agt q-dhcp q-l3 q-meta neutron 

# Dragonflow
#Q_ENABLE_DRAGONFLOW_LOCAL_CONTROLLER=True
#enable_plugin dragonflow https://github.com/openstack/dragonflow.git
#enable_service df-controller
#enable_service db-ext-services
#enable_service q-svc
#enable_service q-l3
#disable_service q-agt
#disable_service n-net

# BGP dynamic routing
#enable_service q-bgp q-bgp-agt
#------------------------------------------------------------------------------
# Glance
enable_service g-api g-reg
#------------------------------------------------------------------------------
# Horizon
enable_service horizon
#------------------------------------------------------------------------------
# Tempest(enabled by default)
#enable_service -tempest
#------------------------------------------------------------------------------
# Heat
#enable_service tempest heat
# Heat - Orchestration Service
#enable_service heat h-api h-api-cfn h-api-cw h-eng
#------------------------------------------------------------------------------
# Swift
# Swift is now used as the back-end for the S3-like object store. If Nova's
# objectstore (``n-obj`` in ``ENABLED_SERVICES``) is enabled, it will NOT
# run if Swift is enabled. Setting the hash value is required and you will
# be prompted for it if Swift is enabled so just set it to something already:
SWIFT_HASH=66a3d6b56c1f479c8b4e70ab5c2000f5
# For development purposes the default of 3 replicas is usually not required.
# Set this to 1 to save some resources:
SWIFT_REPLICAS=1
# The data for Swift is stored by default in (``$DEST/data/swift``),
# or (``$DATA_DIR/swift``) if ``DATA_DIR`` has been set, and can be
# moved by setting ``SWIFT_DATA_DIR``. The directory will be created
# if it does not exist.
SWIFT_DATA_DIR=$DEST/data
#Enable Swift
enable_service s-proxy s-object s-container s-account
#Cyborg
enable_plugin cyborg https://opendev.org/openstack/cyborg
OPAE_INSTALL_ENABLE=false
```

**Comment by jin544642965** [comment]
pycharm 远程调试devstack，发现进入不了断点，求解。
操作步骤：在nova/compute/api.py ,get_all加入断点，systemctl restart devstack@n-api.service服务，在页面点击获取实例，发现进入不了断点，监听信息一次性全打印出来。devstack是当前最新版
![image](https://user-images.githubusercontent.com/18446221/68267129-57ff6c00-008c-11ea-8114-fa2f4cbd5984.png)
